-- =====================================================
-- CORE LAYER - MODELO DIMENSIONAL (STAR SCHEMA)
-- =====================================================

USE SCHEMA CORE_DATA;

-- =====================================================
-- DIMENSÃO TEMPO
-- =====================================================

CREATE OR REPLACE TABLE DIM_TEMPO (
    DATA_KEY NUMBER AUTOINCREMENT,
    DATA_COMPLETA DATE NOT NULL,
    ANO NUMBER NOT NULL,
    MES NUMBER NOT NULL,
    DIA NUMBER NOT NULL,
    TRIMESTRE NUMBER NOT NULL,
    SEMESTRE NUMBER NOT NULL,
    DIA_SEMANA NUMBER NOT NULL,
    NOME_DIA_SEMANA STRING NOT NULL,
    DIA_ANO NUMBER NOT NULL,
    SEMANA_ANO NUMBER NOT NULL,
    MES_NOME STRING NOT NULL,
    MES_NOME_ABREV STRING NOT NULL,
    TRIMESTRE_NOME STRING NOT NULL,
    E_FIM_SEMANA BOOLEAN NOT NULL,
    E_FERIADO BOOLEAN DEFAULT FALSE,
    NOME_FERIADO STRING,
    
    -- Campos para análise de negócio
    E_DIA_UTIL BOOLEAN NOT NULL,
    PERIODO_DIA STRING, -- 'Manhã', 'Tarde', 'Noite'
    ESTACAO_ANO STRING, -- 'Verão', 'Outono', 'Inverno', 'Primavera'
    
    PRIMARY KEY (DATA_KEY),
    UNIQUE (DATA_COMPLETA)
);

-- =====================================================
-- DIMENSÃO PRODUTO
-- =====================================================

CREATE OR REPLACE TABLE DIM_PRODUTO (
    PRODUTO_KEY NUMBER AUTOINCREMENT,
    PRODUTO_ID STRING NOT NULL,
    NOME_PRODUTO STRING NOT NULL,
    DESCRICAO_PRODUTO STRING,
    CATEGORIA_PRINCIPAL STRING,
    SUBCATEGORIA STRING,
    MARCA STRING,
    MODELO STRING,
    COR STRING,
    TAMANHO STRING,
    PESO_GRAMAS NUMBER,
    DIMENSOES STRING,
    
    -- URLs e imagens
    URL_PRODUTO STRING,
    URL_IMAGEM_PRINCIPAL STRING,
    URL_IMAGEM_SECUNDARIA STRING,
    
    -- Classificações e avaliações
    RATING_MEDIO FLOAT,
    NUMERO_AVALIACOES NUMBER,
    
    -- Informações de preço (para análise histórica)
    PRECO_ORIGINAL FLOAT,
    PRECO_ATUAL FLOAT,
    PERCENTUAL_DESCONTO FLOAT,
    
    -- Disponibilidade e estoque
    DISPONIVEL BOOLEAN DEFAULT TRUE,
    ESTOQUE_DISPONIVEL NUMBER,
    
    -- Metadados
    DATA_PRIMEIRA_VENDA DATE,
    DATA_ULTIMA_ATUALIZACAO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS_PRODUTO STRING DEFAULT 'ATIVO', -- 'ATIVO', 'DESCONTINUADO', 'SAZONAL'
    
    -- Campos para análise
    FAIXA_PRECO STRING, -- 'Baixo', 'Médio', 'Alto', 'Premium'
    POPULARIDADE_SCORE NUMBER,
    
    PRIMARY KEY (PRODUTO_KEY),
    UNIQUE (PRODUTO_ID)
);

-- =====================================================
-- DIMENSÃO CLIENTE (Hipotética)
-- =====================================================

CREATE OR REPLACE TABLE DIM_CLIENTE (
    CLIENTE_KEY NUMBER AUTOINCREMENT,
    CLIENTE_ID STRING NOT NULL,
    NOME_CLIENTE STRING,
    EMAIL STRING,
    TELEFONE STRING,
    DATA_NASCIMENTO DATE,
    GENERO STRING,
    
    -- Segmentação
    SEGMENTO_CLIENTE STRING, -- 'Bronze', 'Prata', 'Ouro', 'Platinum'
    SCORE_CREDITO NUMBER,
    RENDA_ESTIMADA_FAIXA STRING,
    
    -- Comportamento
    DATA_PRIMEIRO_PEDIDO DATE,
    DATA_ULTIMO_PEDIDO DATE,
    TOTAL_PEDIDOS_HISTORICO NUMBER DEFAULT 0,
    VALOR_TOTAL_COMPRAS FLOAT DEFAULT 0,
    TICKET_MEDIO FLOAT DEFAULT 0,
    
    -- Status
    STATUS_CLIENTE STRING DEFAULT 'ATIVO', -- 'ATIVO', 'INATIVO', 'SUSPENSO'
    DATA_CADASTRO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DATA_ULTIMA_ATUALIZACAO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    PRIMARY KEY (CLIENTE_KEY),
    UNIQUE (CLIENTE_ID)
);

-- =====================================================
-- DIMENSÃO LOCALIZAÇÃO
-- =====================================================

CREATE OR REPLACE TABLE DIM_LOCALIZACAO (
    LOCALIZACAO_KEY NUMBER AUTOINCREMENT,
    CODIGO_POSTAL STRING NOT NULL,
    CIDADE STRING NOT NULL,
    ESTADO STRING NOT NULL,
    PAIS STRING NOT NULL,
    REGIAO STRING,
    
    -- Coordenadas geográficas
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    
    -- Classificações demográficas
    TIPO_AREA STRING, -- 'Urbana', 'Suburbana', 'Rural'
    DENSIDADE_POPULACIONAL STRING, -- 'Alta', 'Média', 'Baixa'
    RENDA_MEDIA_AREA FLOAT,
    
    -- Informações logísticas
    ZONA_ENTREGA STRING,
    TEMPO_ENTREGA_PADRAO NUMBER, -- em dias
    CUSTO_ENTREGA_BASE FLOAT,
    
    PRIMARY KEY (LOCALIZACAO_KEY),
    UNIQUE (CODIGO_POSTAL, CIDADE, ESTADO, PAIS)
);

-- =====================================================
-- TABELA FATO - VENDAS
-- =====================================================

CREATE OR REPLACE TABLE FATO_VENDAS (
    VENDA_KEY NUMBER AUTOINCREMENT,
    
    -- Chaves estrangeiras (Foreign Keys)
    DATA_KEY NUMBER NOT NULL,
    PRODUTO_KEY NUMBER NOT NULL,
    CLIENTE_KEY NUMBER NOT NULL,
    LOCALIZACAO_KEY NUMBER NOT NULL,
    
    -- Identificadores de negócio
    PEDIDO_ID STRING NOT NULL,
    ITEM_PEDIDO_ID STRING NOT NULL,
    
    -- Métricas (Measures)
    QUANTIDADE_VENDIDA NUMBER NOT NULL,
    PRECO_UNITARIO FLOAT NOT NULL,
    PRECO_TOTAL FLOAT NOT NULL,
    DESCONTO_APLICADO FLOAT DEFAULT 0,
    VALOR_DESCONTO FLOAT DEFAULT 0,
    PRECO_FINAL FLOAT NOT NULL,
    
    -- Custos e margens
    CUSTO_PRODUTO FLOAT,
    MARGEM_BRUTA FLOAT,
    PERCENTUAL_MARGEM FLOAT,
    
    -- Informações de entrega
    CUSTO_ENTREGA FLOAT DEFAULT 0,
    TEMPO_ENTREGA_DIAS NUMBER,
    
    -- Impostos
    VALOR_IMPOSTOS FLOAT DEFAULT 0,
    PERCENTUAL_IMPOSTOS FLOAT DEFAULT 0,
    
    -- Timestamps
    DATA_PEDIDO TIMESTAMP_NTZ NOT NULL,
    DATA_ENTREGA TIMESTAMP_NTZ,
    DATA_PROCESSAMENTO TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Status e controle
    STATUS_VENDA STRING DEFAULT 'CONFIRMADA', -- 'PENDENTE', 'CONFIRMADA', 'CANCELADA', 'DEVOLVIDA'
    CANAL_VENDA STRING DEFAULT 'ONLINE', -- 'ONLINE', 'MOBILE', 'MARKETPLACE'
    
    -- Métricas calculadas
    RECEITA_LIQUIDA FLOAT GENERATED ALWAYS AS (PRECO_FINAL - CUSTO_PRODUTO - CUSTO_ENTREGA),
    
    PRIMARY KEY (VENDA_KEY),
    
    -- Foreign Key Constraints
    FOREIGN KEY (DATA_KEY) REFERENCES DIM_TEMPO(DATA_KEY),
    FOREIGN KEY (PRODUTO_KEY) REFERENCES DIM_PRODUTO(PRODUTO_KEY),
    FOREIGN KEY (CLIENTE_KEY) REFERENCES DIM_CLIENTE(CLIENTE_KEY),
    FOREIGN KEY (LOCALIZACAO_KEY) REFERENCES DIM_LOCALIZACAO(LOCALIZACAO_KEY)
);

-- =====================================================
-- ÍNDICES PARA PERFORMANCE
-- =====================================================

-- Índices na tabela fato
CREATE INDEX IF NOT EXISTS IDX_FATO_VENDAS_DATA ON FATO_VENDAS(DATA_KEY);
CREATE INDEX IF NOT EXISTS IDX_FATO_VENDAS_PRODUTO ON FATO_VENDAS(PRODUTO_KEY);
CREATE INDEX IF NOT EXISTS IDX_FATO_VENDAS_CLIENTE ON FATO_VENDAS(CLIENTE_KEY);
CREATE INDEX IF NOT EXISTS IDX_FATO_VENDAS_LOCALIZACAO ON FATO_VENDAS(LOCALIZACAO_KEY);
CREATE INDEX IF NOT EXISTS IDX_FATO_VENDAS_DATA_PEDIDO ON FATO_VENDAS(DATA_PEDIDO);
CREATE INDEX IF NOT EXISTS IDX_FATO_VENDAS_STATUS ON FATO_VENDAS(STATUS_VENDA);

-- Índices nas dimensões
CREATE INDEX IF NOT EXISTS IDX_DIM_PRODUTO_CATEGORIA ON DIM_PRODUTO(CATEGORIA_PRINCIPAL);
CREATE INDEX IF NOT EXISTS IDX_DIM_PRODUTO_MARCA ON DIM_PRODUTO(MARCA);
CREATE INDEX IF NOT EXISTS IDX_DIM_CLIENTE_SEGMENTO ON DIM_CLIENTE(SEGMENTO_CLIENTE);
CREATE INDEX IF NOT EXISTS IDX_DIM_LOCALIZACAO_ESTADO ON DIM_LOCALIZACAO(ESTADO);
